name: test

on:
  pull_request:


jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo "# test one" >> $GITHUB_STEP_SUMMARY
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
          echo $GITHUB_REPOSITORY
      - name: Print a greeting
        run: |
          echo "# test two" >> $GITHUB_STEP_SUMMARY
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
          echo $GITHUB_REPOSITORY

  my-job2:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo "# test three" >> $GITHUB_STEP_SUMMARY



